name: Restrict Merge to Main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the source branch is HotFix
        run: |
          if [[ "${{ github.head_ref }}" != "HotFix" ]]; then
            echo "Only the 'HotFix' branch can be merged into 'main'."
            exit 1
          fi
        shell: bash
